import {useState,type FormEvent} from 'react';
import {emsSystems,type Meter,type SystemKey} from '../data/devices';
import {useMeterStore} from '../context/MeterStore';
import './Admin.css';
const blank=(system:SystemKey):Meter=>({id:'',name:'',system,systemName:emsSystems.find(x=>x[0]===system)?.[1]||'',equipment:'',location:'',status:'online',kwh:0,kvah:0,kw:0,pf:0.98,voltage:433,voltageUnit:'V',current:0,freq:50,supply:'GRID'});
export default function Admin(){const {meters,add,update,remove,reset}=useMeterStore();const [system,setSystem]=useState<SystemKey>('source');const [editing,setEditing]=useState<string|null>(null);const [form,setForm]=useState<Meter|null>(null);const [error,setError]=useState('');const [authorized,setAuthorized]=useState(sessionStorage.getItem('energyos_demo_admin')==='yes');const [pass,setPass]=useState('');
 const rows=meters.filter(x=>x.system===system);
 const change=(key:keyof Meter,value:string)=>setForm(prev=>prev?({...prev,[key]:['kwh','kvah','kw','pf','voltage','current','freq'].includes(key)?Number(value):value} as Meter):prev);
 const save=(e:FormEvent)=>{e.preventDefault();if(!form)return;const id=form.id.trim();if(!id||!form.name.trim()){setError('MFM ID and name are required');return}if(meters.some(x=>x.id.toLowerCase()===id.toLowerCase()&&x.id!==editing)){setError('MFM ID already exists');return}if(![form.kwh,form.kvah,form.kw,form.pf,form.voltage,form.current,form.freq].every(Number.isFinite)||form.pf<0||form.pf>1){setError('Enter valid numeric readings; PF must be between 0 and 1');return}const value={...form,id,system,systemName:emsSystems.find(x=>x[0]===system)?.[1]||''};if(editing)update(editing,value);else add(value);setForm(null);setEditing(null);setError('')};
 if(!authorized)return <section className="admin-page"><h1>Super Admin (Demo)</h1><p>Local prototype access only. This password does not provide real security.</p><form onSubmit={e=>{e.preventDefault();if(pass==='admin123'){sessionStorage.setItem('energyos_demo_admin','yes');setAuthorized(true);setError('')}else setError('Incorrect demo password')}}><label>Demo password<input type="password" value={pass} onChange={e=>setPass(e.target.value)} /></label><button type="submit">Enter configuration</button>{error&&<p role="alert">{error}</p>}</form><p>Demo password: <code>admin123</code></p></section>;
 return <section className="admin-page"><div className="admin-head"><div><h1>Super Admin · MFM Configuration</h1><p>Assign MFMs to EMS systems. Changes are saved only in this browser.</p></div><button onClick={()=>{sessionStorage.removeItem('energyos_demo_admin');setAuthorized(false)}}>Exit admin</button></div><label>EMS system<select value={system} onChange={e=>{setSystem(e.target.value as SystemKey);setForm(null);setEditing(null)}}>{emsSystems.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><div className="admin-actions"><strong>{rows.length} configured MFMs</strong><button onClick={()=>{setForm(blank(system));setEditing(null);setError('')}}>+ Add MFM</button></div><div className="admin-list">{rows.map(m=><div key={m.id}><div><strong>{m.id}</strong><span>{m.name} · {m.equipment} · {m.location}</span></div><button onClick={()=>{setEditing(m.id);setForm({...m});setError('')}}>Edit</button><button onClick={()=>{if(window.confirm(`Remove ${m.id}?`))remove(m.id)}}>Delete</button></div>)}{!rows.length&&<p>No MFMs assigned. Select Add MFM to create one.</p>}</div>{form&&<form className="admin-form" onSubmit={save}><h2>{editing?'Edit':'Add'} MFM — {emsSystems.find(x=>x[0]===system)?.[1]}</h2><div className="admin-fields">{([['id','MFM ID'],['name','Meter name'],['equipment','Equipment'],['location','Location'],['kwh','kWh'],['kvah','kVAh'],['kw','kW'],['pf','Power factor'],['voltage','Voltage'],['current','Current (A)'],['freq','Frequency (Hz)']] as [keyof Meter,string][]).map(([key,label])=><label key={key}>{label}<input required={key==='id'||key==='name'} type={['kwh','kvah','kw','pf','voltage','current','freq'].includes(key)?'number':'text'} step="any" value={String(form[key])} onChange={e=>change(key,e.target.value)}/></label>)}<label>Voltage unit<select value={form.voltageUnit} onChange={e=>change('voltageUnit',e.target.value)}><option>V</option><option>kV</option></select></label><label>Status<select value={form.status} onChange={e=>change('status',e.target.value)}><option>online</option><option>warning</option><option>offline</option></select></label><label>Supply<select value={form.supply} onChange={e=>change('supply',e.target.value)}><option>GRID</option><option>DG</option><option>STANDBY</option></select></label></div>{error&&<p role="alert">{error}</p>}<div className="admin-actions"><button type="submit">Save MFM</button><button type="button" onClick={()=>setForm(null)}>Cancel</button></div></form>}<p className="admin-note">Prototype: settings are stored in localStorage, not shared across devices. Live readings are demo data. Production requires authenticated API, database, device telemetry, and audit logs.</p><button className="admin-reset" onClick={()=>{if(window.confirm('Restore all original demo meters?'))reset()}}>Restore demo meters</button></section>;
}
