import {useMeterStore} from '../context/MeterStore';
import{useEffect,useMemo,useState}from'react';import{useNavigate,useParams}from'react-router-dom';import{Zap,RadioTower,Gauge,ArrowLeftRight,Activity,Wifi,TriangleAlert,ChevronRight,RefreshCw,Thermometer,Box,Signal,Network,Clock3,ChartNoAxesCombined,ShieldCheck,CircleGauge,PlugZap}from'lucide-react';import{gateways,sensors,converters,loadTrend,energyTrend,emsSystems,type SystemKey}from'../data/devices';
const IconBox=({children}:{children:any})=><div className="iconbox">{children}</div>;
const Status=({s='online'}:{s?:string})=><span className={'status '+s}><i/>{s.toUpperCase()}</span>;
function Spark({data}:{data:number[]}){const max=Math.max(...data),min=Math.min(...data);const pts=data.map((v,i)=>`${(i/(data.length-1))*100},${46-((v-min)/(max-min||1))*38}`).join(' ');return <svg className="spark" viewBox="0 0 100 50" preserveAspectRatio="none"><polyline points={pts}/></svg>}
function PageHead({title,sub}:{title:string,sub:string}){return <div className="pagehead"><div><h1>{title}</h1><p>{sub}</p></div><span className="updated"><RefreshCw/> Updated now</span></div>}
export function Home(){const {meters}=useMeterStore();const [tick,setTick]=useState(0);useEffect(()=>{const x=setInterval(()=>setTick(v=>v+1),2000);return()=>clearInterval(x)},[]);const m=meters[0],kw=m.kw+Math.sin(tick/2)*2.2;return <><PageHead title="Live Monitoring" sub="Essential energy and device health at a glance"/><section className="hero"><div><span className="eyebrow"><Status/> GRID SUPPLY</span><small>ACTIVE POWER</small><strong>{kw.toFixed(1)} <em>kW</em></strong><p><Activity/> Live from {m.id} · updated {tick%3+1}s ago</p></div><div className="heroenergy"><div><span>kWh</span><b>{(m.kwh+tick*.08).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1})}</b><small>IMPORT ENERGY</small></div><div><span>kVAh</span><b>{(m.kvah+tick*.085).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1})}</b><small>APPARENT ENERGY</small></div></div></section><section className="quick"><Metric icon={<Gauge/>} label="Voltage" value={`${(m.voltage+Math.sin(tick)*.8).toFixed(1)} V`}/><Metric icon={<Activity/>} label="Current" value={`${(m.current+Math.cos(tick)*1.7).toFixed(1)} A`}/><Metric icon={<CircleGauge/>} label="Power Factor" value={(m.pf+Math.sin(tick)*.001).toFixed(3)}/><Metric icon={<Zap/>} label="Frequency" value={`${(m.freq+Math.sin(tick)*.01).toFixed(2)} Hz`}/></section><div className="twocol"><section className="panel"><PanelTitle icon={<ChartNoAxesCombined/>} title="Live Load" meta="Last 60 minutes"/><div className="bigchart"><Spark data={loadTrend.map((v,i)=>v+Math.sin(tick+i)*1.2)}/><div className="chartlabels"><span>11:40</span><span>12:00</span><span>12:20</span><span>Now</span></div></div></section><section className="panel"><PanelTitle icon={<Network/>} title="Device Health" meta="29 devices"/><DeviceHealth/></section></div><section className="panel"><PanelTitle icon={<RadioTower/>} title="Monitoring Devices" meta="Tap a category to monitor"/><CategoryGrid/></section></>}
function Metric({icon,label,value}:{icon:any,label:string,value:string}){return <div className="metric"><IconBox>{icon}</IconBox><div><span>{label}</span><b>{value}</b></div></div>}
function PanelTitle({icon,title,meta}:{icon:any,title:string,meta:string}){return <div className="paneltitle"><div>{icon}<b>{title}</b></div><span>{meta}</span></div>}
function DeviceHealth(){const {meters}=useMeterStore();return <div className="health"><div><IconBox><Zap/></IconBox><span><b>EMS</b><small>{meters.length} MFMs</small></span><em>{meters.filter(m=>m.status==='online').length}</em></div><div><IconBox><RadioTower/></IconBox><span><b>Gateways</b><small>3 devices</small></span><em>2 <i>/ 3</i></em></div><div><IconBox><Gauge/></IconBox><span><b>Sensors</b><small>4 devices</small></span><em>4</em></div><div><IconBox><ArrowLeftRight/></IconBox><span><b>Converters</b><small>3 devices</small></span><em>3</em></div></div>}
function CategoryGrid(){const {meters}=useMeterStore();const n=useNavigate();return <div className="categories">{[[Zap,'EMS',`${meters.length} MFMs`,'Systems · MFMs · Live power','meters'],[RadioTower,'Gateways','3 devices','Communication health','gateways'],[Gauge,'Sensors','4 devices','Temperature · Level · Vibration','sensors'],[ArrowLeftRight,'Protocol Converters','3 devices','RS-485 · BLE · Ethernet','converters']].map(([I,t,c,d,k]:any)=><button key={k} onClick={()=>n('/devices/'+k)}><IconBox><I/></IconBox><div><b>{t}</b><span>{d}</span><small>{c} · <em>ONLINE</em></small></div><ChevronRight/></button>)}</div>}
export function Devices(){const {type}=useParams();const [tab,setTab]=useState(type||'meters');useEffect(()=>{if(type)setTab(type)},[type]);return <><PageHead title="Devices" sub="Real-time status of field monitoring devices"/><div className="tabs">{['meters','gateways','sensors','converters'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='meters'?'EMS':t==='converters'?'Protocol Converters':t[0].toUpperCase()+t.slice(1)}</button>)}</div>{tab==='meters'&&<Meters/>}{tab==='gateways'&&<Gateways/>}{tab==='sensors'&&<Sensors/>}{tab==='converters'&&<Converters/>}</>}
function Meters(){const {meters}=useMeterStore();
  const[selectedSystem,setSelectedSystem]=useState<SystemKey|null>(null);
  const[open,setOpen]=useState<string|null>(null);
  const[tick,setTick]=useState(0);
  useEffect(()=>{const x=setInterval(()=>setTick(v=>v+1),2000);return()=>clearInterval(x)},[]);

  if(!selectedSystem){
    return <>
      <div className="emsintro"><div><b>EMS Systems</b><span>Select a system to view its connected MFM meters.</span></div><small>{emsSystems.length} systems · {meters.length} MFMs</small></div>
      <div className="systemgrid">
        {emsSystems.map(([key,name,description])=>{
          const list=meters.filter(m=>m.system===key);
          const online=list.filter(m=>m.status==='online').length;
          const warning=list.some(m=>m.status==='warning');
          return <button className="systemcard" key={key} onClick={()=>{setSelectedSystem(key);setOpen(null)}}>
            <IconBox><Zap/></IconBox>
            <div><b>{name}</b><span>{description}</span><small>{list.length} MFM{list.length===1?'':'s'} · <em className={warning?'warntext':''}>{online} ONLINE</em></small></div>
            <ChevronRight/>
          </button>
        })}
      </div>
    </>
  }

  const system=emsSystems.find(([key])=>key===selectedSystem);
  const systemMeters=meters.filter(m=>m.system===selectedSystem);
  return <>
    <div className="systembar">
      <button onClick={()=>{setSelectedSystem(null);setOpen(null)}}><ChevronRight/> All Systems</button>
      <div><small>EMS SYSTEM</small><b>{system?.[1]}</b><span>{systemMeters.length} connected MFM{systemMeters.length===1?'':'s'}</span></div>
    </div>
    <div className="devicegrid">
      {systemMeters.map((m,i)=><article className={'devicecard '+(open===m.id?'open':'')} key={m.id} onClick={()=>setOpen(open===m.id?null:m.id)}>
        <div className="devicehead"><IconBox><Zap/></IconBox><div><b>{m.id}</b><span>{m.name}</span><small>{m.equipment} · {m.location}</small></div><Status s={m.status}/></div>
        <div className="energyread"><div><span>kWh</span><b>{(m.kwh+(i===0?tick*.08:0)).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1})}</b></div><div><span>kVAh</span><b>{(m.kvah+(i===0?tick*.085:0)).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1})}</b></div></div>
        <div className="minor"><span><small>POWER</small><b>{m.kw.toFixed(1)} kW</b></span><span><small>PF</small><b>{m.pf.toFixed(3)}</b></span><span><small>SUPPLY</small><b>{m.supply}</b></span></div>
        {open===m.id&&<div className="details"><Metric icon={<Gauge/>} label="Voltage" value={`${m.voltage.toFixed(m.voltageUnit==='kV'?2:1)} ${m.voltageUnit}`}/><Metric icon={<Activity/>} label="Current" value={`${m.current.toFixed(1)} A`}/><Metric icon={<Zap/>} label="Frequency" value={`${m.freq.toFixed(2)} Hz`}/><Metric icon={<Clock3/>} label="Update" value="2 sec ago"/></div>}
      </article>)}
    </div>
  </>
}
function Gateways(){return <div className="devicegrid">{gateways.map(g=><article className="devicecard" key={g.id}><div className="devicehead"><IconBox><RadioTower/></IconBox><div><b>{g.id}</b><span>{g.name}</span><small>{g.location}</small></div><Status s={g.status}/></div><div className="gatewayhero"><Signal/><div><small>CONNECTED DEVICES</small><b>{g.devices}</b></div></div><div className="rows"><p><span>Protocol</span><b>{g.protocol}</b></p><p><span>Uplink</span><b>{g.uplink}</b></p><p><span>Signal</span><b>{g.signal}</b></p><p><span>Last packet</span><b>1 sec ago</b></p></div></article>)}</div>}
function Sensors(){const icons:any={Temperature:Thermometer,Level:Gauge,Vibration:Activity};return <div className="devicegrid">{sensors.map(s=>{const I=icons[s.kind];return <article className="devicecard sensor" key={s.id}><div className="devicehead"><IconBox><I/></IconBox><div><b>{s.id}</b><span>{s.name}</span><small>{s.location}</small></div><Status s={s.status}/></div><div className="sensorvalue"><b>{s.value}</b><span>{s.unit}</span><small>{s.kind.toUpperCase()}</small></div></article>})}</div>}
function Converters(){return <div className="devicegrid">{converters.map(c=><article className="devicecard" key={c.id}><div className="devicehead"><IconBox><ArrowLeftRight/></IconBox><div><b>{c.id}</b><span>{c.name}</span><small>{c.location}</small></div><Status s={c.status}/></div><div className="conversion"><div><PlugZap/><b>{c.input}</b></div><ArrowLeftRight/><div><Wifi/><b>{c.output}</b></div></div><div className="rows"><p><span>Baud rate</span><b>{c.baud}</b></p><p><span>Connected to</span><b>{c.device}</b></p><p><span>Communication</span><b className="good">Healthy</b></p><p><span>Last packet</span><b>1 sec ago</b></p></div></article>)}</div>}
export function Energy(){const {meters}=useMeterStore();return <><PageHead title="Energy" sub="Essential consumption monitoring — no unnecessary analytics"/><section className="energytop"><div><IconBox><Zap/></IconBox><span>TOTAL IMPORT</span><b>{meters[0]?.kwh.toLocaleString() ?? "0"} <em>kWh</em></b></div><div><IconBox><Activity/></IconBox><span>APPARENT ENERGY</span><b>{meters[0]?.kvah.toLocaleString() ?? "0"} <em>kVAh</em></b></div></section><section className="panel"><PanelTitle icon={<ChartNoAxesCombined/>} title="Today's Energy" meta="Live cumulative consumption"/><div className="energychart"><Spark data={energyTrend}/></div><div className="chartlabels"><span>06:00</span><span>09:00</span><span>12:00</span><span>Now</span></div></section><section className="panel"><PanelTitle icon={<Zap/>} title="EMS" meta="MFM energy counters"/><div className="meterrows">{meters.map(m=><div key={m.id}><IconBox><Zap/></IconBox><span><b>{m.id}</b><small>{m.name}</small></span><em>{m.kwh.toLocaleString()} <small>kWh</small></em><em>{m.kvah.toLocaleString()} <small>kVAh</small></em><Status s={m.status}/></div>)}</div></section></>}
export function Alerts(){return <><PageHead title="Alerts" sub="Only device and monitoring exceptions requiring attention"/><div className="alerts"><article><IconBox><TriangleAlert/></IconBox><div><b>Gateway communication degraded</b><span>GW-03 · Roof Gateway</span><small>1 downstream device is not responding.</small></div><Status s="warning"/><time>2 min ago</time></article><article><IconBox><TriangleAlert/></IconBox><div><b>DG meter in standby</b><span>MFM-DG-01 · DG Common</span><small>No live voltage detected. DG supply is currently inactive.</small></div><Status s="warning"/><time>18 min ago</time></article></div></>}
export function More(){return <><PageHead title="More" sub="Site and communication information"/><div className="moregrid"><section className="panel"><PanelTitle icon={<Network/>} title="Communication Path" meta="Main incoming meter"/><div className="topology"><Node icon={<Zap/>} t="MFM-SRC-01" s="Source MFM"/><i>Modbus RTU</i><Node icon={<ArrowLeftRight/>} t="CONV-01" s="RS-485 → BLE"/><i>BLE</i><Node icon={<RadioTower/>} t="GW-01" s="Gateway"/><i>Ethernet</i><Node icon={<Box/>} t="BMS" s="Server"/></div></section><section className="panel"><PanelTitle icon={<ShieldCheck/>} title="Site Status" meta="Sky 1"/><div className="rows siteinfo"><p><span>Monitoring devices</span><b>29</b></p><p><span>Online</span><b className="good">28</b></p><p><span>Warnings</span><b>1</b></p><p><span>Data refresh</span><b>2 seconds</b></p><p><span>Primary protocol</span><b>Modbus RTU</b></p></div></section></div></>}
function Node({icon,t,s}:{icon:any,t:string,s:string}){return <div><IconBox>{icon}</IconBox><b>{t}</b><small>{s}</small></div>}
